version: "3.7"

services: 
    mysql:
        image: mysql
        restart: always
        expose: 
            - 3306
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
    adminer:
        image: adminer
        ports: 
            - 8080:8080
        depends_on: 
            - mysql
        